services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"    # MQTT port
      - "9001:9001"    # WebSocket port (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - app-network

  graphql:
    build: .
    container_name: graphql
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    env_file:
      - .env
    networks:
      - app-network
    # Uncomment if you need to mount volumes for development
    # volumes:
    #   - .:/app

networks:
  app-network:
    driver: bridge

volumes:
  mosquitto-data:
  mosquitto-log:
