[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
 "fastapi>=0.116.1",
 "paho-mqtt>=2.1.0",
 "python-dotenv>=1.1.1",
 "strawberry-graphql>=0.278.1",
 "uvicorn[standard]>=0.35.0",
]
